# Generated by Django 6.0.2 on 2026-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portfolio_remove_blog_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
